name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .Net SDK
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
      
    #   - name: Run tests
    #     run: dotnet test